### ISSUE TITLE
Bug: ♾ loop with `no_user_input`

### ISSUE THREAD

**Issue by mklaber** [wayfair-incubator/columbo#357]
In a typical session, if a question has a validator and the user provides an invalid value, it'll re-ask the question until they've answered it correctly. When `no_user_input` is set to `True`, there's no opportunity for the user to provide a value. Instead, it relies on the `default` value to actually be valid. There are cases, particularly when the `default` is a callable, that the value provided to `default` is itself invalid. In this case, the `.ask` goes in to an infinite loop.

Suggested fix: if `no_user_input` is set to `True`, and validation fails, raise an error.

```python
def _default_val(_: Answers):
    return "invalid"

def _validator(value: str, _: Answers):
    return ValidationFailure(error=f"{value} is bad") if value == "invalid" else ValidationSuccess()

loopy_question = BasicQuestion(
    "loopy_question",
    "Will you plz stop?",
    default=_default_val,
    validator=_validator
)

_ = loopy_question.ask(SOME_ANSWERS, no_user_input=True)
```

**Comment by plannigan** [comment]
This might be something that could be made clearer in the documentation, but the expectation is that the default should always be valid. Trying to have the code enforce that gets tricky since both might be expecting the `Answers` argument to have values. So I don't think it would be possible to ensure when creating the question.

However, it should be possible to detect the issue when it happens. This would raise an error as it is an invalid state.
